### ISSUE TITLE
Header width should be set by the same limit governing page width

### ISSUE THREAD

**Issue by connerk** [rogue-hack-lab/rhl-new#1]
I think it's `<div class="container">`

**Comment by Pater1** [comment]
Any pages with layout-representative content? All I'm seeing are (what I assume to be) 'TODO' markers like these: 
![index](https://cloud.githubusercontent.com/assets/4977838/24925632/18b577ac-1eb6-11e7-9777-f6598ea2b956.PNG)

**Comment by pcunning** [comment]
@Pater1 you need to follow the directions for building locally. These use Jekyll to build the pages. Once we have enough to change the live site to this one GitHub will build the pages on every push and host them with gh-pages.

**Comment by connerk** [comment]
@Pater1 
jekyll uses a number of syntax to automate building static sites. https://jekyllrb.com/
what you are seeing are the 2 things
- everything between --- HERE --- is front matter syntax. variables that Jekyll will pass around and reference during the build
- {% stuff in here %} => this is the liquid templating syntax. use of front matter and references to files in the app.

**Comment by pcunning** [comment]
fixed in #20
