### ISSUE TITLE
all paypal values are not unique

### ISSUE THREAD

**Issue by jarmstro** [rogue-hack-lab/rhl-new#10]
in  rhl-new/_includes/donate.html
does it matter that there are two lines in the select block with the same value?
it is those with:
<option value="Supporting Member">...

please pardon my html noobness if it doesn't matter here.  thanks.

**Comment by connerk** [comment]
Which lines are you seeing?

**Comment by jarmstro** [comment]
whoops, clearly brackets must be some meta-character in these boxes.
the missing line after "it is those with:" is
...option value="Supporting Member"...

there's two of those values.  the $10/mo  and the $60/year ones

**Comment by connerk** [comment]
I do see line 16 & 23 now.. 
is Paypal cool with this, @pcunning?

**Comment by jarmstro** [comment]
I see from the html docs that duplicate values are ok syntactically, but how will the two donation values be differentiated by paypal unless it could read the corresponding text element?

**Comment by pcunning** [comment]
The form seems to work successfully leading me to believe PayPal is looking at the text. There might be some configure on the PayPal side but I haven't looked.

**Comment by connerk** [comment]
I don't think anyone has ever hit that $60 button..

**Comment by pcunning** [comment]
Yeah. Just tried. It does not work. Should we just remove it? I wonder if we can configure that form to allow a one time donation?

**Comment by jarmstro** [comment]
Ok,  sorry for the red herring. I withdraw my issue.
I found that the select property 'selectedIndex' can be used to identify a selection, in addition to its 'value'.
Also all the options text can be read by iterating over the   SelectionTag's   .options[i].text  property
That allows one to see all about the original selection list info as well as the selected item info.

**Comment by connerk** [comment]
I went to paypal and fixed the button. 
added a one-time-contribution button while I was at it. still a bit of formatting to do but it's there and tested. :)

**Comment by connerk** [comment]
c5dff4180cd908e60ad42222a62b34948c08470b
