### ISSUE TITLE
possible typos

### ISSUE THREAD

**Issue by jarmstro** [rogue-hack-lab/rhl-new#11]

**Comment by jarmstro** [comment]
1.
in rhl-new/_includes/footer.html

 Build with  ... -> Built with ...


2.
in each of:
underscore projects/Micro-Drone-Race-Installation.md
underscore projects/Photo-Booth.md
underscore projects/Secrets-of-Locks.md
underscore projects/translux.md
underscore projects/3D-Printing.md
underscore projects/Pixual.md
underscore projects/[TEMPLATE]-project.md

there is:
# sit organizational properties. don't change this

should 'sit' be 'site'?

**Comment by jarmstro** [comment]
Sorry, I'm going to have to learn about the meta-character usage in these text boxes.
the pound-sign made a large bold font out of my line.
I will read the markdown docs next.

**Comment by connerk** [comment]
Yep, that should be Site.
Bummer... That's not generative so I'll have to fix em all! 
Fortunately they are just comments so no harm to the site and won't be seen by users.

**Comment by pcunning** [comment]
@connerk did you fix this?

**Comment by connerk** [comment]
Not yet

**Comment by connerk** [comment]
fixed with commit b49cc9efb7367e85f24fb3d4abd319bad334ec6e
