### ISSUE TITLE
Google Analytics Visable

### ISSUE THREAD

**Issue by mobieonekinobi** [rogue-hack-lab/rhl-new#17]
Dig the new RHL site. But just a note on Google Analytics...if you didn't already know or if it's even a concern for you, but SHIFT + U on the new RHL site shows your Google Analytics id in the footer. You may want to hide that so it doesn't get hacked. I am a PHP'er and in PHP there's a difference in how to hide it when it's in the header vs the footer. Not sure if any of this is a factor for you guys but wanted to let you know. Cheers!

**Comment by connerk** [comment]
Google Analytics ID at _config.yml line 37

**Comment by connerk** [comment]
This method meets all standard implementation practices. 
GA IDs are white listed to specific domains.
