### ISSUE TITLE
Slide Out Menu stays open

### ISSUE THREAD

**Issue by connerk** [rogue-hack-lab/rhl-new#2]
[Desktop, Chrome]

When the slide out menu is opened by the user, it remains open even while `:hover` is false or other page interactions are happening

**Comment by pcunning** [comment]
https://github.com/mango/slideout#how-to-add-an-overlay-to-close-the-menu-on-click

**Comment by Pater1** [comment]
Implemented, writing up pull request now.

**Comment by pcunning** [comment]
fixed in #20
